language: node_js
node_js:
  - "14.16"
services: mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ts_express_boilerplate_test;'
script: mkdir -p ./dist/logs ./dist/env ./dist/public/archives ./dist/public/documents ./dist/public/audios ./dist/public/videos ./dist/public/images/master-copy ./dist/public/images/rescale/xs ./dist/public/images/rescale/sm ./dist/public/images/rescale/md ./dist/public/images/rescale/lg ./dist/public/images/rescale/xl && cp ./src/env/template.env ./dist/env/development.env && cp ./src/env/template.env ./dist/env/test.env && npm i typescript -g && npm i typeorm -g && npm i && tsc && typeorm schema:sync && env ENVIRONMENT=test env RUNNER=travis npm run ci:test
after_success: npm run ci:coverage
cache:
  directories:
    - "node_modules"