language: node_js
node_js:
  - "14.16"
services: mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS typeplate_test;'
script: mkdir -p ./dist/logs ./dist/env ./dist/public/archives ./dist/public/documents ./dist/public/audios ./dist/public/videos ./dist/public/images/master-copy ./dist/public/images/rescale && cp ./src/env/template.env ./dist/env/test.env && npm i typescript -g && npm i typeorm -g && npm i && tsc && typeorm schema:sync && npm run ci:test
after_success: npm run ci:coverage
cache:
  directories:
    - "node_modules"